# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "computeDayHours": "00_core.ipynb",
         "computeDayHoursRest": "00_core.ipynb",
         "loadData": "00_core.ipynb",
         "generatePerDayStats": "00_core.ipynb",
         "generateUMStats": "00_core.ipynb",
         "writeData": "00_core.ipynb",
         "getSpark": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://radhakrishnavuppala.github.io/jupyter_dev_lib/"

git_url = "https://github.com/radhakrishnavuppala/jupyter_dev_lib/tree/master/"

def custom_doc_links(name): return None
